const imageMap: Record<string, any> = {
  "alegria.png": require("../assets/images/emociones/alegria.png"),
  "tristeza.png": require("../assets/images/emociones/tristeza.png"),
  "enfado.png": require("../assets/images/emociones/enfado.png"),
  "miedo.png": require("../assets/images/emociones/miedo.png"),
  "asco.png": require("../assets/images/emociones/asco.png"),
  "verguenza.png": require("../assets/images/emociones/verguenza.png"),
  "calma.png": require("../assets/images/emociones/calma.png"),
  "confusion.png": require("../assets/images/emociones/confusion.png"),
  "sorpresa.png": require("../assets/images/emociones/sorpresa.png"),
  "orgullo.png": require("../assets/images/emociones/orgullo.png"),
  "celos.png": require("../assets/images/emociones/celos.png"),
  "aburrimiento.png": require("../assets/images/emociones/aburrimiento.png"),
  "cansancio.png": require("../assets/images/emociones/cansancio.png"),
  "ilusion.png": require("../assets/images/emociones/ilusion.png"),
  "frustracion.png": require("../assets/images/emociones/frustracion.png"),
  "cariño.png": require("../assets/images/emociones/cariño.png"),
  "ansiedad.png": require("../assets/images/emociones/ansiedad.png"),
  "gratitud.png": require("../assets/images/emociones/gratitud.png"),
  "soledad.png": require("../assets/images/emociones/soledad.png"),
  "esperanza.png": require("../assets/images/emociones/esperanza.png"),
  "inseguridad.png": require("../assets/images/emociones/inseguridad.png"),
  "curiosidad.png": require("../assets/images/emociones/curiosidad.png"),
  "culpa.png": require("../assets/images/emociones/culpa.png"),
  "empatia.png": require("../assets/images/emociones/empatia.png"),
  "serenidad.png": require("../assets/images/emociones/serenidad.png"),
  "rabia.png": require("../assets/images/emociones/rabia.png"),
  "euforia.png": require("../assets/images/emociones/euforia.png"),
  "agobio.png": require("../assets/images/emociones/agobio.png"),
  "desconfianza.png": require("../assets/images/emociones/desconfianza.png"),
  "admiracion.png": require("../assets/images/emociones/admiracion.png"),
  "alivio.png": require("../assets/images/emociones/alivio.png"),
  "preocupacion.png": require("../assets/images/emociones/preocupacion.png"),
  "pena.png": require("../assets/images/emociones/pena.png"),
  "rechazo.png": require("../assets/images/emociones/rechazo.png"),
  "gracia.png": require("../assets/images/emociones/gracia.png"),
  "caso1.png": require("../assets/images/casos/caso1.png"),
  "caso2.png": require("../assets/images/casos/caso2.png"),
  "caso3.png": require("../assets/images/casos/caso3.png"),
  "caso4.png": require("../assets/images/casos/caso4.png"),
  "caso5.png": require("../assets/images/casos/caso5.png"),
};

export default imageMap;
